variable "aws_region" {
  description = "Region for the stack. The CloudFront certificate is always issued in us-east-1 regardless."
  type        = string
  default     = "us-east-1"
}

variable "project_name" {
  description = "Short name used as a prefix for every resource."
  type        = string
  default     = "reconai"
}

variable "environment" {
  description = "Environment name. This stack is designed for a single short-lived 'demo'."
  type        = string
  default     = "demo"
}

variable "domain_name" {
  description = <<-EOT
    Public hostname for the console. A subdomain only.

    DNS stays authoritative at Namecheap; Terraform manages no zone and creates
    no Route 53 records. It outputs the two CNAMEs to add by hand. The apex
    (pragatinarote.com) is live and must never be touched.
  EOT
  type        = string
  default     = "reconai.pragatinarote.com"
}

variable "deploy_app_services" {
  description = <<-EOT
    Stage gate. Leave false for the first apply.

    false -> foundation only: VPC, RDS, ECR, ALB, CloudFront, S3, Cloud Map,
             IAM, log groups. No ECS tasks run, so nothing waits on images or
             secrets that do not exist yet.
    true  -> starts kafka, financial-core and investigation-service.

    Set true only after images are pushed and both SSM SecureStrings exist.
    See README.md. Using this flag rather than `-target` keeps both applies
    reproducible and fully described in version control.
  EOT
  type        = bool
  default     = false
}

# --- Secret parameter NAMES (metadata, not values) --------------------------

variable "anthropic_key_parameter_name" {
  description = <<-EOT
    Name of the SSM SecureString holding the Anthropic API key.

    Terraform does NOT create this parameter and does NOT read its value. Only
    the name and the derived ARN enter state. Create it out-of-band; see README.
  EOT
  type        = string
  default     = "/reconai/demo/anthropic-api-key"
}

variable "agent_database_url_parameter_name" {
  description = <<-EOT
    Name of the SSM SecureString holding the Investigation Service's composed
    asyncpg database URL.

    Composed rather than assembled from parts because the application's config
    takes a single URL, and ECS cannot template a URL around a secret. Created
    out-of-band between the two applies; see README.
  EOT
  type        = string
  default     = "/reconai/demo/agent-database-url"
}

# --- Demo access gate -------------------------------------------------------

variable "basic_auth_username" {
  description = <<-EOT
    Username for the CloudFront Basic Auth gate. Not a secret.

    The password is GENERATED by Terraform (random_password) rather than taken
    as a variable, so no real credential ever needs to be typed into tfvars or
    risk being committed. Read it after apply with:
      terraform output -raw basic_auth_password

    CloudFront Functions have no network access, so the credential must be
    embedded in the function at deploy time and therefore exists in Terraform
    state. That is accepted: its only power is gating a synthetic-data demo.
  EOT
  type        = string
  default     = "reconai"
}

# --- GitHub OIDC ------------------------------------------------------------

variable "github_owner" {
  description = "GitHub org/user that owns the repository, for the OIDC trust policy."
  type        = string
  default     = "PragatiAN1109"
}

variable "github_repo" {
  description = "Repository name, for the OIDC trust policy."
  type        = string
  default     = "ReconAI"
}

variable "create_github_oidc_provider" {
  description = <<-EOT
    Whether to create the GitHub OIDC provider in this account.

    An account can hold only ONE provider for token.actions.githubusercontent.com.
    Set false if it already exists (another project created it) and supply
    existing_github_oidc_provider_arn instead.
  EOT
  type        = bool
  default     = true
}

variable "existing_github_oidc_provider_arn" {
  description = "ARN of a pre-existing GitHub OIDC provider. Used only when create_github_oidc_provider is false."
  type        = string
  default     = ""
}

# --- Sizing -----------------------------------------------------------------

variable "db_instance_class" {
  description = "RDS instance class. The workload is a handful of rows."
  type        = string
  default     = "db.t4g.micro"
}

variable "log_retention_days" {
  description = "CloudWatch log retention. Unbounded retention is a slow cost leak."
  type        = number
  default     = 7
}

variable "image_tag" {
  description = "Container image tag that ECS should run. Overridden by CI on deploy."
  type        = string
  default     = "latest"
}
